# Generated by Django 4.2.6 on 2023-12-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sensores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('numero1', models.IntegerField()),
                ('numero2', models.IntegerField()),
                ('numero3', models.FloatField()),
                ('booleano', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='NumerosModel',
        ),
    ]
