# Generated by Django 4.2.6 on 2023-12-05 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0002_sensores_delete_numerosmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensores',
            name='created',
        ),
    ]
