# Generated by Django 4.2.6 on 2023-12-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioarduino',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usuarioarduino',
            name='dispositivo_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
