# Generated by Django 4.2.6 on 2023-12-11 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sensores', '0003_rename_nombre_usuarioarduino_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioarduino',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
