# Generated by Django 4.2.6 on 2023-12-11 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sensores', '0004_alter_usuarioarduino_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioarduino',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to=settings.AUTH_USER_MODEL),
        ),
    ]
