# Generated by Django 4.2.6 on 2023-12-11 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensores', '0008_alter_datosdispositivo_dispositivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosdispositivo',
            name='dispositivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datos_dispositivos', to='sensores.usuarioarduino'),
        ),
    ]
