# Generated by Django 4.2.6 on 2023-12-16 18:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sensores', '0012_alter_datosdispositivo_dispositivo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsuarioArduino',
            new_name='UsuarioDispositivo',
        ),
    ]
