# Generated by Django 4.2.6 on 2023-12-23 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensores', '0013_rename_usuarioarduino_usuariodispositivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosdispositivo',
            name='dispositivo',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='Datos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('temp', models.FloatField()),
                ('hum', models.FloatField()),
                ('limo', models.FloatField()),
                ('detec', models.BooleanField()),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datos_dispositivos', to='sensores.usuariodispositivo')),
            ],
        ),
    ]
