# Generated by Django 4.2.6 on 2023-12-26 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensores', '0015_delete_datosdispositivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datos',
            old_name='detec',
            new_name='lemo',
        ),
        migrations.RenameField(
            model_name='datos',
            old_name='limo',
            new_name='ppm',
        ),
    ]
