# Generated by Django 4.2.6 on 2023-12-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sensores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero1', models.IntegerField()),
                ('numero2', models.IntegerField()),
            ],
        ),
    ]
